apiVersion: V1
kind: Application
metadata:
  name: springboot-first-app
  namespace: tejaswiini
spec:
  project: default

  source:
    repoURL: https://github.com/tejaswini-arc/springboot-first-app.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: tejaswiini

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true