apiVersion: V1
kind: Application
metadata:
  name: myapp-V1
  namespace: teju
spec:
  project: default

  source:
    repoURL: https://github.com/tejaswini-arc/springboot-first-app.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: spring-boot-k8s

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true